base_model: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
# I'm training on 4090 GPUs
# so I'm using 4-bit precision to save on memory
load_in_4bit: true
strict: false

data_seed: 42
seed: 42

datasets:
  - path: data/sharegpt_isaf_press_releases_ft_train.jsonl
    type: sharegpt
    conversation: alpaca
dataset_prepared_path:
val_set_size: 0.1
output_dir: ./outputs/tiny-llama/lora-out-sharegpt
hub_model_id: strickvl/isafpr-tiny-llama-lora-sharegpt

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: isaf_pr_ft
wandb_entity: strickvl
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
